## Enable NodeJS or QuickJS usage for YouTube, both options can be uncommented.
## Please see notes as to why you might want to consider carefully when enabling
## https://github.com/yt-dlp/yt-dlp/wiki/EJS#step-1-install-a-supported-javascript-runtime
# --js-runtimes node
# --js-runtimes bun
# --js-runtimes quickjs

## Enable remote components in Deno and Bun, useful to fetch required Ejs scripts
## https://github.com/yt-dlp/yt-dlp/wiki/EJS#step-2-install-ejs-challenge-solver-scripts
# --remote-components ejs:github
# --remote-components ejs:npm
