# fstab.conf on Warpnix, penguins-eggs 26.6.2
---
crypttabOptions: luks,keyscript=/bin/cat
efiMountOptions: umask=0077
tmpOptions:
  default:
    tmpfs: false
    options: ''
  ssd:
    tmpfs: true
    options: defaults,noatime,mode=1777
