# shellprocess@boot_reconfigure.conf on Warpnix, penguins-eggs 26.6.2
---
message: Final reconfiguration of the kernel and bootloader...
dontChroot: false
timeout: 300
script:
  - chmod 644 /boot/vmlinuz-`uname -r`
  - chown 0:0 /boot/vmlinuz-`uname -r`
  - INITRD=No dpkg-reconfigure -fnoninteractive linux-image-`uname -r`
