# shellprocess@install_translations.conf on Warpnix, penguins-eggs 26.6.2
---
message: installation of translation packages...
dontChroot: false
timeout: 1800
script:
  - /usr/libexec/calamares/calamares-l10n-helper.sh
