# shellprocess@boot_deploy.conf on Warpnix, penguins-eggs 26.6.2
---
message: Preparing the boot environment...
dontChroot: true
timeout: 300
script:
  - >-
    cp --preserve=timestamps /run/live/medium/live/vmlinuz-`uname -r`
    ${ROOT}/boot/vmlinuz-`uname -r`
