# shellprocess@mkinitramfs.conf on Warpnix, penguins-eggs 26.6.2
---
message: Creating the boot image (initramfs)...
dontChroot: false
timeout: 300
script:
  - mkinitramfs -o /boot/initrd.img-$(uname -r)
