# welcome.conf on Warpnix, penguins-eggs 26.6.2
---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true
requirements:
  internetCheckUrl: http://networkcheck.kde.org
  requiredStorage: 8
  requiredRam: 1
  check:
    - storage
    - ram
    - power
    - internet
    - root
  required:
    - root
    - storage
    - ram
