# Subscription configuration file for CUPS v2.4.16
# Written by cupsd
NextSubscriptionId 177
<Subscription 175>
Events printer-changed
Owner cups-browsed
LeaseDuration 86400
Interval 60
ExpirationTime 1784327538
NextEventId 1
</Subscription>
<Subscription 176>
Events all
Owner anonymous
Recipient dbus://
LeaseDuration 86400
Interval 0
ExpirationTime 1784327538
NextEventId 1
</Subscription>
