#!/bin/sh

# if the current release is under development there won't be a new one
if grep -q "^PRETTY_NAME=.*(development branch)" /etc/os-release; then
    exit 0
fi

# if it is non-root user, skip
if [ $(id -u) -ne 0 ]; then
    exit 0
fi

if [ -x /usr/lib/ubuntu-release-upgrader/release-upgrade-motd ]; then
    exec /usr/lib/ubuntu-release-upgrader/release-upgrade-motd
fi
