[General]
bgColor=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
fallbackIconTheme=oxygen
fullScreenBgColor=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
maxRecentFiles=5
recentlyOpenedFiles=/home/warpdev/Downloads/hello/hello-world/logo.png, /home/warpdev/Downloads/hello/hello-world/background.png, /home/warpdev/Downloads/hello/hello-world/ubuntu_logo16.png, /home/warpdev/Downloads/hello/hello-world/logo_blurred.png
slideShowInterval=5
solidBg=true
sorting=name

[Thumbnail]
MaxThumbnailFileSize=4096
ShowThumbnails=false
ThumbnailSize=64
ThumbnailsPosition=bottom

[Window]
ColorSpace=1
ExifDatakWidth=250
FixedHeight=480
FixedWidth=640
ForceZoomFit=false
LastWindowHeight=718
LastWindowMaximized=false
LastWindowWidth=1149
PrefSize=@Size(400 400)
ShowAnnotationsToolbar=false
ShowExifData=false
ShowMenubar=true
ShowOutline=false
ShowToolbar=true
SmoothOnZoom=true
UseTrash=true
